cloud:
  aws:
    credentials:
      access-key: AKIA2LVXZB6L46BWYMAL
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: pushkarawsbucket


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

